###
GET http://localhost:4000/api/especialistas

###
POST http://localhost:4000/api/especialistas/registro

###
PUT http://localhost:4000/api/especialistas/10

###
DELETE http://localhost:4000/api/especialistas/4